version: '3'

services:
  squid:
    image: ubuntu/squid:latest
    container_name: squid-proxy
    ports:
      - "8080:3128"  # Relai Web (HTTP & HTTPS)
      - "8530:3128"  # Relai de mise à jour Windows (WSUS)
      - "53:53/udp"  # Relai de résolution de noms (DNS)
    volumes:
      - ./squid.conf:/etc/squid/squid.conf
      - ./squid_logs:/var/log/squid
    restart: always
    networks:
      - vch_network
    command: >
      sh -c "mkdir -p /var/log/squid && 
             chmod -R 777 /var/log/squid && 
             squid -f /etc/squid/squid.conf -N"
    cap_add:
      - NET_ADMIN  # Nécessaire pour configurer iptables
    extra_hosts:
      - "restricted.domain:127.0.0.1"  # Bloque certains domaines critiques

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command: '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    restart: always
    networks:
      - vch_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "veolia_secure_password"
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_INSTALL_PLUGINS: "grafana-piechart-panel"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: always
    networks:
      - vch_network
    depends_on:
      - prometheus

networks:
  vch_network:
    driver: bridge
    internal: true  # Empêche l'accès direct à Internet

volumes:
  grafana-data:
