version: "3.9"

networks:
  infra_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "10.0.0.0/24"  # Plage d'adresses IP pour votre réseau Docker
        - gateway: "10.0.0.1"     # Passerelle par défaut du réseau

services:
  ntp_service:
    build: ./ntp
    container_name: ntp_service
    restart: always
    networks:
      infra_net:
        ipv4_address: "10.0.0.10"  # Adresse IP statique
    ports:
      - "123:123/udp"

  log_service:
    build: ./log_service
    container_name: log_service
    restart: always
    networks:
      infra_net:
        ipv4_address: "10.0.0.20"  # Adresse IP statique
    ports:
      - "514:514/udp"
      - "8514:8514"

  compliance_agent:
    build: ./compliance_agent
    container_name: compliance_agent
    restart: always
    networks:
      infra_net:
        ipv4_address: "10.0.0.30"  # Adresse IP statique

  proxy_service:
    build: ./proxy_service
    container_name: proxy_service
    restart: always
    networks:
      infra_net:
        ipv4_address: "10.0.0.40"  # Adresse IP statique
    ports:
      - "8080:8080"
      - "8530:8530"
      - "53:53/udp"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    networks:
      infra_net:
        ipv4_address: "10.0.0.50"  # Adresse IP statique
    ports:
      - "3000:3000"  # Accès à l'interface Web de Grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Définir le mot de passe admin
    volumes:
      - grafana_data:/var/lib/grafana  # Persistance des données

volumes:
  grafana_data:  # Volume Docker pour la persistance des données