networks:
  infra_net:
    driver: bridge
    ipam:
      config:
        - subnet: "10.0.0.0/24"
          gateway: "10.0.0.1"

services:
  log_service:
    build:
      context: ./log_service
      dockerfile: Dockerfile
    container_name: log_service
    restart: always
    networks:
      infra_net:
        ipv4_address: "10.0.0.20"
    ports:
      - "514:514/udp"           # Port d'écoute pour les journaux Syslog
      - "8514:8514"             # Port pour l'interface de visualisation
    volumes:
      - ./logs/syslog.log:/var/log/syslog.log
      - ./log_service/certs:/etc/rsyslog/certs  # Certificats TLS
    environment:
      SOC_IP_1: "10.0.0.80"
      SOC_IP_2: "10.0.1.82"
      SOC_PORT: "6514"

  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: always
    networks:
      infra_net:
        ipv4_address: "10.0.0.60"
    ports:
      - "3100:3100"
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/local-config.yaml
      - loki_data:/etc/loki
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    restart: always
    networks:
      infra_net:
        ipv4_address: "10.0.0.70"
    volumes:
      - ./logs:/var/log
      - ./loki/promtail-config.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    networks:
      infra_net:
        ipv4_address: "10.0.0.50"
    ports:
      - "3000:3000"             # Port interne de Grafana
      - "8514:3000"             # Exposition sur le port 8514 du VCH
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_INSTALL_PLUGINS: grafana-loki-datasource
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data:
  loki_data: