auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: /etc/loki
  storage:
    filesystem:
      chunks_directory: /etc/loki/chunks
      rules_directory: /etc/loki/rules

promtail:
  config_file: /etc/promtail/promtail-config.yaml
