auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095

common:
  instance_name: loki
  path_prefix: /tmp/loki
  replication_factor: 1
  retention_period: 7d  # Période de rétention des logs
  retention_deletes_enabled: true
  compaction:
    compaction_retention_enabled: true

ingester:
  chunk_target_size: 1048576
  max_chunk_age: 1h
  chunk_idle_period: 5m
  max_chunk_count: 5000

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index:
        prefix: index_
        period: 168h

ruler:
  alertmanager_url: http://localhost:9093

storage_config:
  boltdb_shipper:
    active_index_directory: /tmp/loki/index
    cache_location: /tmp/loki/cache
  filesystem:
    directory: /tmp/loki/chunks

compactor:
  working_directory: /tmp/loki/compactor

limits_config:
  max_streams_per_user: 10000
  max_line_size: 1048576
