auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: /etc/loki
  storage:
    filesystem:
      chunks_directory: /etc/loki/chunks
      rules_directory: /etc/loki/rules
  retention_period: 744h  # 1 mois
  retention_deletes_enabled: true